# Generated by Django 3.0.2 on 2020-01-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0002_auto_20200110_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='played',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.AddField(
            model_name='profile',
            name='fourths',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seconds',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='thirds',
            field=models.IntegerField(default='0'),
        ),
    ]
