# Generated by Django 3.0.2 on 2020-01-14 17:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0004_auto_20200114_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rolls',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
