# Generated by Django 3.0.2 on 2020-01-14 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ludo', '0007_auto_20200114_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='total_players',
        ),
        migrations.AddField(
            model_name='game',
            name='players_played',
            field=models.ManyToManyField(blank=True, related_name='ludo_played', to=settings.AUTH_USER_MODEL),
        ),
    ]
