# Generated by Django 3.0.2 on 2020-01-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludo', '0008_auto_20200114_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fourths',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seconds',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thirds',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wins',
        ),
        migrations.AddField(
            model_name='profile',
            name='first',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='fourth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='third',
            field=models.IntegerField(default=0),
        ),
    ]
