# Generated by Django 3.0.1 on 2019-12-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
