# Generated by Django 3.0.1 on 2019-12-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191223_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_before_deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_days',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_hours',
            field=models.IntegerField(default='0'),
        ),
    ]
