# Generated by Django 3.0.2 on 2020-01-13 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_carrier', to=settings.AUTH_USER_MODEL)),
                ('passengers', models.ManyToManyField(blank=True, related_name='transport_passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
