# Generated by Django 3.0.2 on 2020-01-16 19:13

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20200116_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='departure_location',
            field=models.CharField(choices=[('MB', 'Maribor'), ('LJ', 'Ljubljana'), ('KP', 'Koper'), ('CE', 'Celje'), ('MS', 'Murska Sobota')], default='MB', max_length=2),
        ),
        migrations.AddField(
            model_name='transport',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='luggage_per_passenger',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transport',
            name='max_passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transport',
            name='passing_locations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MB', 'Maribor'), ('LJ', 'Ljubljana'), ('KP', 'Koper'), ('CE', 'Celje'), ('MS', 'Murska Sobota')], max_length=2),
        ),
        migrations.AddField(
            model_name='transport',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='transport',
            name='target_location',
            field=models.CharField(choices=[('MB', 'Maribor'), ('LJ', 'Ljubljana'), ('KP', 'Koper'), ('CE', 'Celje'), ('MS', 'Murska Sobota')], default='LJ', max_length=2),
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_brand',
            field=models.CharField(choices=[('MITS', 'Mitsubishi'), ('AUDI', 'Audi'), ('BMW', 'Bmw'), ('CITR', 'Citroen')], default='MITS', max_length=4),
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_color',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_type',
            field=models.CharField(choices=[('C', 'Car'), ('V', 'Van'), ('T', 'Truck'), ('L', 'Limousine')], default='C', max_length=1),
        ),
    ]
