# Generated by Django 3.0.2 on 2020-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_auto_20200116_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='target_location',
            new_name='arrival_location',
        ),
        migrations.AlterField(
            model_name='transport',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
