# Generated by Django 3.0.2 on 2020-01-16 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0007_transport_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='passengers_confirmed',
            field=models.ManyToManyField(blank=True, related_name='transport_passenger_confirmed', to=settings.AUTH_USER_MODEL),
        ),
    ]
