# Generated by Django 3.0.2 on 2020-01-16 23:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_transport_passengers_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='passing_locations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MB', 'Maribor'), ('LJ', 'Ljubljana'), ('KP', 'Koper'), ('CE', 'Celje'), ('MS', 'Murska Sobota')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vehicle_brand',
            field=models.CharField(blank=True, choices=[('MITS', 'Mitsubishi'), ('AUDI', 'Audi'), ('BMW', 'Bmw'), ('CITR', 'Citroen')], max_length=4),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('C', 'Car'), ('V', 'Van'), ('T', 'Truck'), ('L', 'Limousine')], max_length=1),
        ),
    ]
