# Generated by Django 3.0.2 on 2020-01-16 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0009_auto_20200117_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='passengers_picked',
            field=models.ManyToManyField(blank=True, related_name='transport_passenger_picked', to=settings.AUTH_USER_MODEL),
        ),
    ]
