# Generated by Django 3.0.2 on 2020-01-16 23:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_transport_passengers_picked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='passing_locations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MB', 'Maribor'), ('LJ', 'Ljubljana'), ('KP', 'Koper'), ('CE', 'Celje'), ('MS', 'Murska Sobota')], max_length=2),
        ),
    ]
