# Generated by Django 3.0.2 on 2020-01-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20200117_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='departed',
            field=models.BooleanField(default=False),
        ),
    ]
