# Generated by Django 3.0.2 on 2020-01-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_transport_departed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='max_passengers',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.DecimalField(decimal_places=2, default=15.95, max_digits=6),
        ),
    ]
