# Generated by Django 3.0.2 on 2020-01-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_auto_20200117_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='completed',
            new_name='arrived',
        ),
    ]
